/**
 * Build identity (P2-E15-15) — "which build am I running?", answerable from
 * inside the app.
 *
 * The motivating failure: a hand-tester ran a stale `out/` build of `main`,
 * read its old bugs as a PR failing, and burned a whole diagnostic cycle before
 * anyone thought to ask which bytes were actually on screen.
 *
 * Two numbers, deliberately separate:
 *
 * - **`package.json` semver** — the human-bumped RELEASE number. It moves when
 *   someone decides it moves, and says nothing about which commit built.
 * - **This identity** — git short SHA + branch + dirty flag + build time,
 *   stamped in at BUILD time by `electron.vite.config.ts` (`define`), which
 *   makes it move with the code for free.
 *
 * Why not a per-build counter in a committed file: with parallel PRs open, a
 * file bumped by every PR is a guaranteed merge conflict between every pair of
 * them. The git SHA already *is* the per-build identity, and it is conflict-
 * free by construction.
 *
 * **Fail-open (a hard constraint):** git may be missing, the tree may be an
 * exported tarball, the define may be absent entirely (vitest imports this
 * module with no bundler in sight). Every one of those degrades to "unknown"
 * and the app still runs — a build must never fail because it could not
 * describe itself.
 */

/**
 * **Moving or renaming this file has a build consequence (#630).** It is the
 * only module the `__SWITCHBOARD_BUILD__` define is substituted into, so the
 * renderer build pins it by path and emits it as its own unhashed chunk to keep
 * the timestamp out of every other chunk's content hash. See
 * `src/build/stamp-chunk.ts`; its test fails if this path stops existing.
 */

/** What the build knew about itself. Every field is nullable on purpose. */
export interface BuildIdentity {
  /** git short SHA at build time, or null when git could not be asked */
  commit: string | null;
  /** branch name at build time; null when detached or unknown */
  branch: string | null;
  /** the working tree had uncommitted changes when this was built */
  dirty: boolean;
  /** ISO-8601 timestamp of the build, or null */
  builtAt: string | null;
}

/** What every fail-open path lands on. */
export const UNKNOWN_BUILD_IDENTITY: BuildIdentity = {
  commit: null,
  branch: null,
  dirty: false,
  builtAt: null,
};

/** The branch a "this is just main" build comes from. */
export const RELEASE_BRANCH = 'main';

declare global {
  /**
   * Injected by `electron.vite.config.ts` into all three build targets. Typed
   * as possibly-undefined because vitest (and any other non-bundled consumer)
   * never sees the define at all — `buildIdentity()` is the only thing that
   * should touch it.
   */
  const __SWITCHBOARD_BUILD__: BuildIdentity | undefined;
}

/**
 * Coerce whatever arrived into a BuildIdentity. The define is generated by our
 * own config, so this is not defence against an attacker — it is defence
 * against a half-written define surviving a refactor and handing the title bar
 * `undefined` to concatenate.
 */
export function normalizeIdentity(raw: unknown): BuildIdentity {
  if (!raw || typeof raw !== 'object') return UNKNOWN_BUILD_IDENTITY;
  const o = raw as Partial<Record<keyof BuildIdentity, unknown>>;
  const str = (v: unknown): string | null => (typeof v === 'string' && v.length > 0 ? v : null);
  return {
    commit: str(o.commit),
    branch: str(o.branch),
    dirty: o.dirty === true,
    builtAt: str(o.builtAt),
  };
}

/** The identity stamped into THIS build, or all-unknown when there is none. */
export function buildIdentity(): BuildIdentity {
  // Written as a ternary rather than an early return because a bundler
  // `define` substitutes the identifier textually — including inside `typeof`
  // — so both arms must survive that substitution unchanged.
  const injected: unknown =
    typeof __SWITCHBOARD_BUILD__ === 'undefined' ? undefined : __SWITCHBOARD_BUILD__;
  return normalizeIdentity(injected);
}

/**
 * The one-glance stamp: `a1b2c3d8`, or `a1b2c3d8*` when the tree was dirty.
 * Null when git was unavailable — callers translate that, because "unknown" is
 * a word and words go through i18n (§5.21).
 */
export function commitStamp(id: BuildIdentity): string | null {
  if (!id.commit) return null;
  return id.dirty ? `${id.commit}*` : id.commit;
}

/**
 * True for a build that came off a clean `main`. Everything else — a feature
 * branch, a dirty tree, a detached checkout, an unknown provenance — is a build
 * a hand-tester should be told about without having to go looking, which is why
 * the window title only grows a suffix when this is false.
 */
export function isReleaseBuild(id: BuildIdentity): boolean {
  return id.branch === RELEASE_BRANCH && !id.dirty && id.commit !== null;
}

/**
 * The OS window title. Plain app name for a clean `main` build; anything else
 * gets the branch and SHA appended, so "am I running the branch I think I am?"
 * is answerable from the taskbar without focusing the window.
 *
 * Not translated: main has no i18n runtime (its dialogs are hardcoded English
 * too), and this is mostly punctuation around raw git data.
 */
export function windowTitle(appName: string, id: BuildIdentity): string {
  if (isReleaseBuild(id)) return appName;
  const stamp = commitStamp(id);
  if (!stamp) return `${appName} — unknown build`;
  return `${appName} — ${id.branch ?? 'detached'} · ${stamp}`;
}

/** How old the build is, in the largest unit that still reads sensibly. */
export interface BuildAge {
  unit: 'now' | 'minutes' | 'hours' | 'days';
  value: number;
}

/**
 * Age of the build at `now`. The single most useful field for the failure this
 * item exists to kill: a build from four days ago is a stale `out/`, whatever
 * its SHA claims.
 *
 * A build time in the future (clock skew, or a machine that travelled) clamps
 * to "just now" rather than rendering a negative count.
 */
export function buildAge(builtAt: string | null, now: Date = new Date()): BuildAge | null {
  if (!builtAt) return null;
  const then = Date.parse(builtAt);
  if (Number.isNaN(then)) return null;
  const minutes = Math.floor((now.getTime() - then) / 60_000);
  if (minutes < 1) return { unit: 'now', value: 0 };
  if (minutes < 60) return { unit: 'minutes', value: minutes };
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return { unit: 'hours', value: hours };
  return { unit: 'days', value: Math.floor(hours / 24) };
}
