// Checksum verification (P2-E19-04).
//
// The parser half is tested against the format `scripts/sha256-sidecar.js`
// actually writes — that script has its own tests for the writing side, and
// these two files are the two halves of one contract. The lenience is
// deliberate and tested as such: a sidecar regenerated by hand with
// `Get-FileHash` (uppercase) or `sha256sum -b` (a `*` marker) must still work,
// because the alternative is an update that silently refuses to install.
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { hashFile, parseSidecar, verifyChecksum } from './verify';
import { cleanupTempDirs, tempDir } from '../../test-temp-dirs';

/**
 * The line `scripts/sha256-sidecar.js` writes, reproduced rather than imported
 * — that script is CommonJS with no types, and `scripts/sha256-sidecar.test.js`
 * already pins its output against this exact shape. Two spellings of one
 * format, each tested against the side that owns it.
 */
const sidecarLine = (hash: string, name: string): string =>
  `${hash}  ${path.basename(name)}\n`;

let dir: string;
let file: string;
const CONTENT = 'pretend this is 120 MB of NSIS installer';
const DIGEST = crypto.createHash('sha256').update(CONTENT).digest('hex');

beforeEach(() => {
  dir = tempDir('sb-verify-');
  file = path.join(dir, 'switchboard-Setup-9.9.9.exe');
  fs.writeFileSync(file, CONTENT);
});
// One directory per test, deleted at the end of that test (#213, #360). Nothing
// here holds a handle: `hashFile` streams and closes before the assertion.
afterEach(() => cleanupTempDirs());

describe('parsing the sidecar', () => {
  it('reads the exact format the release workflow writes', () => {
    // Not a paraphrase of the format — the real writer, imported.
    const line = sidecarLine(DIGEST, 'C:\\build\\dist\\switchboard-Setup-9.9.9.exe');
    expect(parseSidecar(line)).toBe(DIGEST);
  });

  it('tolerates the ways a human might regenerate one', () => {
    expect(parseSidecar(`${DIGEST}  file.exe\r\n`)).toBe(DIGEST);
    expect(parseSidecar(`${DIGEST} *file.exe\n`)).toBe(DIGEST);
    expect(parseSidecar(`  ${DIGEST}\n`)).toBe(DIGEST);
    expect(parseSidecar(DIGEST)).toBe(DIGEST);
    expect(parseSidecar(DIGEST.toUpperCase())).toBe(DIGEST); // Get-FileHash
  });

  it('refuses anything that is not exactly one digest', () => {
    expect(parseSidecar('')).toBeNull();
    expect(parseSidecar('not a hash at all')).toBeNull();
    expect(parseSidecar(DIGEST.slice(0, 63))).toBeNull(); // one nibble short
    expect(parseSidecar(`${DIGEST}0`)).toBeNull();
    expect(parseSidecar(`${DIGEST}  a.exe\n${DIGEST}  b.exe\n`)).toBeNull(); // two files
    expect(parseSidecar(null)).toBeNull();
    expect(parseSidecar(42)).toBeNull();
    // an HTML error page saved as a sidecar — the shape of a proxy interfering
    expect(parseSidecar('<!doctype html><title>404</title>')).toBeNull();
  });
});

describe('verifying a file', () => {
  it('matches the real digest of real bytes', async () => {
    expect(await hashFile(file)).toBe(DIGEST);
    expect(await verifyChecksum(file, sidecarLine(DIGEST, 'switchboard-Setup-9.9.9.exe'))).toBe(
      true
    );
  });

  it('says NO to a single flipped byte — the case this exists for', async () => {
    fs.writeFileSync(file, CONTENT.replace('120', '121'));
    expect(await verifyChecksum(file, sidecarLine(DIGEST, 'x.exe'))).toBe(false);
  });

  it('says NO to a truncated download', async () => {
    fs.writeFileSync(file, CONTENT.slice(0, 10));
    expect(await verifyChecksum(file, sidecarLine(DIGEST, 'x.exe'))).toBe(false);
  });

  it('says NO — never throws — when the sidecar is junk or the file is missing', async () => {
    expect(await verifyChecksum(file, 'garbage')).toBe(false);
    expect(await verifyChecksum(path.join(dir, 'nope.exe'), sidecarLine(DIGEST, 'x'))).toBe(false);
    expect(await verifyChecksum(file, undefined)).toBe(false);
  });
});
