// Checksum verification (P2-E19-04, plan §E19).
//
// **This is the reason an unsigned build is acceptable at all.** There is no
// code signature on the installer (E19 decision 3 — a per-user NSIS install
// needs no UAC and the in-app download applies no Mark-of-the-Web), so the
// sha256 sidecar is the ONLY thing standing between "bytes that arrived" and
// "an executable we start". A mismatch is not a retry and not a warning: the
// file is deleted and the user is sent to the release page in their browser.
//
// It is TOFU and we say so out loud (decision 3): the checksum and the
// installer come from the same feed, so this proves the bytes are the bytes
// GitHub vouched for — not that GitHub is who we think it is. TLS does that
// half. What it genuinely catches is the case that actually happens: a
// truncated or corrupted download, which would otherwise be launched as an
// executable.
//
// The format is `scripts/sha256-sidecar.js`'s, and that script's header states
// the contract this parser is the other half of: `<64 lowercase hex><two
// spaces><basename><LF>`.
import crypto from 'crypto';
import fs from 'fs';

const HEX64 = /^[0-9a-f]{64}$/;

/**
 * The digest out of a sidecar file's text, or null.
 *
 * Deliberately lenient about EVERYTHING except the digest: any leading
 * whitespace, `\r\n`, a `*name` (sha256sum's binary marker), a missing file
 * name. The first whitespace-delimited token is the contract — the rest of the
 * line is for humans and for `sha256sum -c`. Case is normalized because
 * `Get-FileHash` and `certutil` both emit uppercase, and a sidecar someone
 * regenerated by hand should not silently fail to match.
 *
 * Refuses a file with more than one line, though: two digests is a sidecar we
 * do not understand, and guessing which one governs an executable is not a
 * thing to do.
 */
export function parseSidecar(text: unknown): string | null {
  if (typeof text !== 'string') return null;
  const lines = text.split('\n').filter((l) => l.trim());
  if (lines.length !== 1) return null;
  const token = lines[0].trim().split(/\s+/)[0]?.toLowerCase() ?? '';
  return HEX64.test(token) ? token : null;
}

/**
 * SHA-256 of a file, lowercase hex.
 *
 * STREAMED, unlike `scripts/sha256-sidecar.js`'s deliberate `readFileSync`:
 * that runs in a CI job that has nothing else to do, this runs in the main
 * process of an app hosting live agent sessions, and reading 120 MB into a
 * Buffer there is a stall every session in the window would feel.
 */
export function hashFile(file: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash('sha256');
    const stream = fs.createReadStream(file);
    stream.on('error', reject);
    stream.on('data', (chunk) => hash.update(chunk));
    stream.on('end', () => resolve(hash.digest('hex')));
  });
}

/**
 * Does `file` hash to what `sidecarText` says? Never throws.
 *
 * Every unhappy answer — unreadable file, unparseable sidecar, wrong digest —
 * is the same `false`, because the consequence is the same: do not run it.
 * `timingSafeEqual` is not used and would be theatre: nothing here is a secret
 * and there is no oracle to time.
 */
export async function verifyChecksum(file: string, sidecarText: unknown): Promise<boolean> {
  const expected = parseSidecar(sidecarText);
  if (!expected) return false;
  let actual: string;
  try {
    actual = await hashFile(file);
  } catch {
    return false;
  }
  return actual === expected;
}
